services:

  backend:

    image: ${DOCKERHUB_USERNAME}/urjasathi-backend:${IMAGE_TAG}

    container_name: urjasathi-backend

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "8000"


  frontend:

    image: ${DOCKERHUB_USERNAME}/urjasathi-frontend:${IMAGE_TAG}

    container_name: urjasathi-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"
      - "443:443"
      
    volumes:
      - /etc/letsencrypt/live/urjasathi.online:/etc/letsencrypt/live/urjasathi.online:ro
      - /etc/letsencrypt/archive/urjasathi.online:/etc/letsencrypt/archive/urjasathi.online:ro